"""
Email Sender Utility
====================
Handles sending investment reports via Gmail SMTP.
"""

import os
import sys
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from email.mime.base import MIMEBase
from email import encoders
from datetime import datetime
from typing import Optional

# Add parent directory to path for imports
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from config import (
    GMAIL_ADDRESS,
    GMAIL_APP_PASSWORD,
    RECIPIENT_EMAIL,
    SMTP_SERVER,
    SMTP_PORT,
    VERBOSE,
)


class EmailSender:
    """
    Handles sending emails via Gmail SMTP with TLS.
    """

    def __init__(
        self,
        sender_email: Optional[str] = None,
        sender_password: Optional[str] = None,
        recipient_email: Optional[str] = None,
    ):
        """
        Initialize the email sender.

        Args:
            sender_email: Gmail address (defaults to config)
            sender_password: Gmail app password (defaults to config)
            recipient_email: Recipient email address (defaults to config)
        """
        self.sender_email = sender_email or GMAIL_ADDRESS
        self.sender_password = sender_password or GMAIL_APP_PASSWORD
        self.recipient_email = recipient_email or RECIPIENT_EMAIL
        self.smtp_server = SMTP_SERVER
        self.smtp_port = SMTP_PORT

    def _convert_to_html(self, text_content: str) -> str:
        """
        Convert markdown-style text to basic HTML for email.

        Args:
            text_content: Plain text or markdown content

        Returns:
            HTML-formatted content
        """
        html_content = text_content

        # Convert markdown headers to HTML
        lines = html_content.split("\n")
        converted_lines = []

        for line in lines:
            if line.startswith("## "):
                converted_lines.append(f"<h2 style='color: #2c3e50; border-bottom: 2px solid #3498db; padding-bottom: 5px;'>{line[3:]}</h2>")
            elif line.startswith("### "):
                converted_lines.append(f"<h3 style='color: #34495e;'>{line[4:]}</h3>")
            elif line.startswith("- "):
                converted_lines.append(f"<li style='margin: 5px 0;'>{line[2:]}</li>")
            elif line.startswith("|"):
                # Table row - basic styling
                converted_lines.append(line)
            elif line.strip() == "---":
                converted_lines.append("<hr style='border: 1px solid #bdc3c7; margin: 20px 0;'>")
            elif line.strip() == "":
                converted_lines.append("<br>")
            else:
                converted_lines.append(f"<p style='margin: 10px 0;'>{line}</p>")

        html_body = "\n".join(converted_lines)

        # Wrap in HTML template
        html_template = f"""
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <style>
        body {{
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            line-height: 1.6;
            color: #2c3e50;
            max-width: 800px;
            margin: 0 auto;
            padding: 20px;
            background-color: #f8f9fa;
        }}
        .container {{
            background-color: white;
            padding: 30px;
            border-radius: 10px;
            box-shadow: 0 2px 10px rgba(0,0,0,0.1);
        }}
        table {{
            width: 100%;
            border-collapse: collapse;
            margin: 15px 0;
        }}
        th, td {{
            border: 1px solid #ddd;
            padding: 10px;
            text-align: left;
        }}
        th {{
            background-color: #3498db;
            color: white;
        }}
        tr:nth-child(even) {{
            background-color: #f2f2f2;
        }}
        .header {{
            text-align: center;
            margin-bottom: 30px;
        }}
        .header h1 {{
            color: #2c3e50;
            margin: 0;
        }}
        .header p {{
            color: #7f8c8d;
            margin: 5px 0;
        }}
        .footer {{
            margin-top: 30px;
            padding-top: 20px;
            border-top: 1px solid #ddd;
            text-align: center;
            color: #7f8c8d;
            font-size: 12px;
        }}
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>Investment Advisory Report</h1>
            <p>Generated on {datetime.now().strftime("%B %d, %Y at %H:%M")}</p>
        </div>
        {html_body}
        <div class="footer">
            <p>This report was generated by the Investment Advisor Multi-Agent System.</p>
            <p>DISCLAIMER: This is for informational purposes only and does not constitute investment advice.</p>
        </div>
    </div>
</body>
</html>
"""
        return html_template

    def send_email(
        self,
        subject: str,
        body: str,
        attachments: Optional[list[str]] = None,
        html: bool = True,
    ) -> bool:
        """
        Send an email with optional attachments.

        Args:
            subject: Email subject
            body: Email body content
            attachments: Optional list of file paths to attach
            html: If True, convert body to HTML

        Returns:
            True if email sent successfully, False otherwise
        """
        try:
            # Create message
            msg = MIMEMultipart("alternative")
            msg["Subject"] = subject
            msg["From"] = self.sender_email
            msg["To"] = self.recipient_email

            # Add body
            if html:
                html_content = self._convert_to_html(body)
                msg.attach(MIMEText(body, "plain"))
                msg.attach(MIMEText(html_content, "html"))
            else:
                msg.attach(MIMEText(body, "plain"))

            # Add attachments
            if attachments:
                for filepath in attachments:
                    if os.path.exists(filepath):
                        with open(filepath, "rb") as f:
                            part = MIMEBase("application", "octet-stream")
                            part.set_payload(f.read())
                            encoders.encode_base64(part)
                            filename = os.path.basename(filepath)
                            part.add_header(
                                "Content-Disposition",
                                f"attachment; filename= {filename}",
                            )
                            msg.attach(part)

                        if VERBOSE:
                            print(f"[EmailSender] Attached: {filename}")
                    else:
                        print(f"[EmailSender] Warning: Attachment not found: {filepath}")

            # Connect and send
            if VERBOSE:
                print(f"[EmailSender] Connecting to {self.smtp_server}:{self.smtp_port}...")

            with smtplib.SMTP(self.smtp_server, self.smtp_port) as server:
                server.starttls()
                server.login(self.sender_email, self.sender_password)
                server.send_message(msg)

            if VERBOSE:
                print(f"[EmailSender] Email sent successfully to {self.recipient_email}")

            return True

        except smtplib.SMTPAuthenticationError:
            print("[EmailSender] Error: Authentication failed. Check your email and app password.")
            return False
        except smtplib.SMTPException as e:
            print(f"[EmailSender] SMTP Error: {str(e)}")
            return False
        except Exception as e:
            print(f"[EmailSender] Error sending email: {str(e)}")
            return False


def send_investment_report(
    decision_content: str,
    research_files: Optional[list[str]] = None,
    discussion_files: Optional[list[str]] = None,
    include_attachments: bool = False,
) -> bool:
    """
    Convenience function to send the investment advisory report.

    Args:
        decision_content: The final decision content from the Decider Agent
        research_files: Optional list of research report file paths
        discussion_files: Optional list of discussion output file paths
        include_attachments: Whether to include reports as attachments

    Returns:
        True if email sent successfully
    """
    current_date = datetime.now().strftime("%Y-%m-%d")
    subject = f"Investment Advisory Report - {current_date}"

    attachments = None
    if include_attachments:
        attachments = []
        if research_files:
            attachments.extend([f for f in research_files if f])
        if discussion_files:
            attachments.extend([f for f in discussion_files if f])

    sender = EmailSender()
    return sender.send_email(
        subject=subject,
        body=decision_content,
        attachments=attachments,
        html=True,
    )


if __name__ == "__main__":
    # Test email sending
    test_content = """
## INVESTMENT ADVISORY SUMMARY
- Report Date: 2026-01-13
- Generated By: Investment Decider Agent

## 1. MARKET OVERVIEW
This is a test email from the Investment Advisor System.

## 2. KEY SUGGESTIONS
| Priority | Suggestion | Asset Class |
|----------|------------|-------------|
| 1 | Test suggestion | Test |

---

This is a test message.
"""

    success = send_investment_report(test_content)
    print(f"Email sent: {success}")
